3094867 js navigation
Lullabot/olivero-poc pull request #19
Opened 2019-11-16 17:10 UTC by vulcanr

Closes https://www.drupal.org/project/olivero/issues/3094867

2019-11-16 17:49 UTC, mherchel requested changes
There's merge conflicts. Some of these issues are already resolved (like use of  aria-popup)

2019-11-16 17:49 UTC, mherchel commented on src/css/components/header.css
> +// Styles to be displayed if JS is not present
You need to use `/* normal css comments */`

2019-11-16 17:49 UTC, mherchel commented on src/css/components/nav-primary.css
> +    &[aria-expanded="false"] {
This issue has been taken care of and merged. It looks like you're starting point was old.

2019-11-17 18:09 UTC, mherchel requested changes

2019-11-17 18:09 UTC, mherchel commented on index.html
> +            <div class="grid-full grid-full-no-js">
Adding the class by default, and then removing it in the JS has the potential to create a flash of unstyled content -- especially for users on slow connections.

A better way would be making use of the the `js` CSS class that Drupal inserts onto the body field when JavaScript is enabled. 

```css
html:not(.js) .site-header__inner .grid-full { ... }
```

Use that in conjunction with a stylesheet that's added within a `<noscript>` tag, and we won't have any flash of unstyled content.

2019-11-17 18:09 UTC, mherchel commented on src/css/components/header.css
> +.js-header-nav {
Move this to a noscript.css file (see prev comment)

2019-11-17 18:09 UTC, mherchel commented on src/js/navigation.js
> +      mobileNavButton.setAttribute('aria-pressed', 'true');
Per Andrew, we do not want to use `aria-pressed`

2019-11-17 18:09 UTC, mherchel commented on src/js/second-level-navigation.js
>    });
Instead of using an anonymous function, you can simplify this to 

```js
subNavButton.addEventListener('click', expandSubNav);
```

2019-11-21 18:27 UTC, vulcanr commented on index.html
> +            <p>Ducimus adipisci placeat excepturi, doloremque praesentium aspernatur laudantium nostrum minima deserunt,
I agree on this one. This was caused from the merge conflicts. Should not happen again

2019-12-09 14:29 UTC, mherchel requested changes

2019-12-09 14:29 UTC, mherchel commented on src/js/navigation.js
> +      mobileNavButton.setAttribute('aria-pressed', 'true');
Still gotta remove the aria-pressed attributes.

2019-12-30 15:25 UTC, proeung commented
@vulcanr When you have a moment, can you take a look at @mherchel 's comments. We'd like to close out this issue soon. Thanks! :)

2019-12-30 15:26 UTC, vulcanr commented
> @vulcanr When you have a moment, can you take a look at @mherchel 's comments. We'd like to close out this issue soon. Thanks! :)

Yep! I'm aiming to close this, on the next days!

2021-07-20 19:56 UTC, closed without merging