3091875: fixing primary nav items wrap text as per proof of concept.
Lullabot/olivero-poc pull request #21
Opened 2019-12-12 10:43 UTC by sreenivasbttv

This PR fixes wrap the text for primary navigation 1st level menu links.
Also as per Figma designs, medium device resolution has 27px of margin-right. So updated according to the design value.

2019-12-29 02:18 UTC, proeung requested changes
@sreenivasbttv Thanks for opening this PR! The no-wrap property looks great, however, we might need to adjust the grid column of the primary menu as the links are currently overlapping on top of the logo (see attached).

![Olivero_Proof_of_Concept](https://user-images.githubusercontent.com/1815714/71551510-56c92c00-29b7-11ea-8904-e72edc48448f.jpg)

**Preview Link:** https://deploy-preview-21--olivero-poc.netlify.com/

I'm adding @jwitkowski79, our primary designer of this project so that she can review your changes as well. Thanks again for contributing to the POC project!

2020-01-06 15:22 UTC, sreenivasbttv commented
@proeung ,

after using no-wrap all menu links shown in a single row. To control overlapping on the logo we must control the max-width of navigation. 
@jwitkowski79 please let us know your point of view if more links are there in navigation how we show or any visual difference?

2020-01-07 14:41 UTC, jwitkowski79 commented
Hi @sreenivasbttv and @proeung!
A couple of ideas that I have for when the menu starts to overlap the logo:

- Can the logo area become smaller? Maybe reduce the padding on either side by 18px. We can also reduce the size of the logo.
- We have a design for longer menus. It basically collapses into the tablet menu. See "Long Menu (Desktop)" at [https://www.figma.com/file/x5zBLbvoW1jsvyAOt4Gp9I/Olivero-Theme-Public?node-id=0%3A1](https://www.figma.com/file/x5zBLbvoW1jsvyAOt4Gp9I/Olivero-Theme-Public?node-id=0%3A1). 

Let me know if any the the above works. If not, I can brainstorm a couple of other ideas.
Thanks,
Jen

2020-01-07 16:56 UTC, proeung commented
@jwitkowski79 Thanks for the response! Yes, I need reducing the size of the logo area will definitely help with the overlapping issue, however, we also need to set a max-width for the primary nav container for when there is a lot of level 0 menu items.

2020-01-09 11:50 UTC, sreenivasbttv commented
@proeung ,

`max-width` has been given to primary navigation (**nav** element) and given overflow-x to auto for scrolling if required.  So please review and let me know if any changes required.

Note: As per the current design, if we wrap menu links to a new row more space will be visible between rows. So I though overflow-x is the best option.

2020-03-10 14:12 UTC, closed without merging